module.exports = [
    'Rick Sanchez',
    'Morty Smith',
    'Summer Smith',
    'Beth Smith',
    'Jerry Smith',
    'Abadango Cluster Princess',
    'Abradolf Lincler',
    'Adjudicator Rick',
    'Agency Director',
    'Alan Rails',
    'Albert Einstein',
    'Alexander',
    'Alien Googah',
    'Alien Morty',
    'Alien Rick',
    'Amish Cyborg',
    'Annie',
    'Antenna Morty',
    'Antenna Rick',
    'Ants in my Eyes Johnson',
    'Aqua Morty',
    'Aqua Rick',
    'Arcade Alien',
    'Armagheadon',
    'Armothy',
    'Arthricia',
    'Artist Morty',
    'Attila Starwar',
    'Baby Legs',
    'Baby Poopybutthole',
    'Baby Wizard',
    'Bearded Lady',
    'Beebo',
    'Benjamin',
    'Bepisian',
    'Beta-Seven',
    'Beth Sanchez',
    'Beth Smith',
    'Beth Smith',
    "Beth's Mytholog"
];
